USE [UNOMVC]

GO
ALTER PROCEDURE uspShiftDetails
(
@ActionCommand varchar(20),
@SHIFT_ID int = null,
@SHIFT_CODE nvarchar(30)=null
,@SHIFT_DESCRIPTION nvarchar(100)=null
,@SHIFT_ALLOCATION_TYPE nvarchar(100)=null
,@SHIFT_AUTO_SEARCH_START datetime=null
,@SHIFT_AUTO_SEARCH_END datetime=null
,@SHIFT_TYPE nvarchar(20)=null
,@SHIFT_START datetime=null
,@SHIFT_END datetime=null
,@SHIFT_BREAK_START datetime=null
,@SHIFT_BREAK_END datetime=null
,@SHIFT_BREAK_HRS datetime=null
,@SHIFT_WORKHRS datetime=null
,@SHIFT_FLAG_ADD_BREAK bit=null
,@SHIFT_WEEKEND_DIFF_TIME bit=null
,@SHIFT_WEEKEND_START datetime=null
,@SHIFT_WEEKEND_END datetime=null
,@SHIFT_WEEKEND_BREAK_START datetime=null
,@SHIFT_WEEKEND_BREAK_END datetime=null
,@SHIFT_EARLY_SEARCH_HRS varchar(20)=null
,@SHIFT_LATE_SEARCH_HRS varchar(20)=null
,@SHIFT_ISDELETED bit=0
,@SHIFT_DELETEDDATE datetime=null
,@SHIFT_START_EARLY_SEARCH_HRS datetime=null
,@SHIFT_START_LATE_SEARCH_HRS datetime=null
,@SHIFT_START_EARLY_VALID_HRS datetime=null
,@SHIFT_START_LATE_VALID_HRS datetime=null
,@SHIFT_BREAK_OUT_EARLY_SEARCH_HRS datetime=null
,@SHIFT_BREAK_OUT_LATE_SEARCH_HRS datetime=null
,@SHIFT_BREAK_OUT_EARLY_VALID_HRS datetime=null
,@SHIFT_BREAK_OUT_LATE_VALID_HRS datetime=null
,@SHIFT_BREAK_IN_EARLY_SEARCH_HRS datetime=null
,@SHIFT_BREAK_IN_LATE_SEARCH_HRS datetime=null
,@SHIFT_BREAK_IN_EARLY_VALID_HRS datetime=null
,@SHIFT_BREAK_IN_LATE_VALID_HRS datetime=null
,@SHIFT_END_EARLY_SEARCH_HRS datetime=null
,@SHIFT_END_LATE_SEARCH_HRS datetime=null
,@SHIFT_END_EARLY_VALID_HRS datetime=null
,@SHIFT_END_LATE_VALID_HRS datetime=null
,@SHIFT_BREAK_OUT_IN_MIN_DUR datetime=null
,@IS_SYNC bit=0
,@COMPANY_ID int=null
)
AS

if(@ActionCommand='Insert')
--INSERT ShiftDetails
BEGIN
INSERT INTO [dbo].[TA_SHIFT]
           ([SHIFT_CODE]
           ,[SHIFT_DESCRIPTION]
           ,[SHIFT_ALLOCATION_TYPE]
           ,[SHIFT_AUTO_SEARCH_START]
           ,[SHIFT_AUTO_SEARCH_END]
           ,[SHIFT_TYPE]
           ,[SHIFT_START]
           ,[SHIFT_END]
           ,[SHIFT_BREAK_START]
           ,[SHIFT_BREAK_END]
           ,[SHIFT_BREAK_HRS]
           ,[SHIFT_WORKHRS]
           ,[SHIFT_FLAG_ADD_BREAK]
           ,[SHIFT_WEEKEND_DIFF_TIME]
           ,[SHIFT_WEEKEND_START]
           ,[SHIFT_WEEKEND_END]
           ,[SHIFT_WEEKEND_BREAK_START]
           ,[SHIFT_WEEKEND_BREAK_END]
           ,[SHIFT_EARLY_SEARCH_HRS]
           ,[SHIFT_LATE_SEARCH_HRS]
           ,[SHIFT_ISDELETED]
           ,[SHIFT_DELETEDDATE]
           ,[SHIFT_START_EARLY_SEARCH_HRS]
           ,[SHIFT_START_LATE_SEARCH_HRS]
           ,[SHIFT_START_EARLY_VALID_HRS]
           ,[SHIFT_START_LATE_VALID_HRS]
           ,[SHIFT_BREAK_OUT_EARLY_SEARCH_HRS]
           ,[SHIFT_BREAK_OUT_LATE_SEARCH_HRS]
           ,[SHIFT_BREAK_OUT_EARLY_VALID_HRS]
           ,[SHIFT_BREAK_OUT_LATE_VALID_HRS]
           ,[SHIFT_BREAK_IN_EARLY_SEARCH_HRS]
           ,[SHIFT_BREAK_IN_LATE_SEARCH_HRS]
           ,[SHIFT_BREAK_IN_EARLY_VALID_HRS]
           ,[SHIFT_BREAK_IN_LATE_VALID_HRS]
           ,[SHIFT_END_EARLY_SEARCH_HRS]
           ,[SHIFT_END_LATE_SEARCH_HRS]
           ,[SHIFT_END_EARLY_VALID_HRS]
           ,[SHIFT_END_LATE_VALID_HRS]
           ,[SHIFT_BREAK_OUT_IN_MIN_DUR]
           ,[IS_SYNC]
           ,[COMPANY_ID])
     VALUES
           (@SHIFT_CODE
           ,@SHIFT_DESCRIPTION
           ,@SHIFT_ALLOCATION_TYPE
           ,@SHIFT_AUTO_SEARCH_START
           ,@SHIFT_AUTO_SEARCH_END
           ,@SHIFT_TYPE
           ,@SHIFT_START
           ,@SHIFT_END
           ,@SHIFT_BREAK_START
           ,@SHIFT_BREAK_END
           ,@SHIFT_BREAK_HRS
           ,@SHIFT_WORKHRS
           ,@SHIFT_FLAG_ADD_BREAK
           ,@SHIFT_WEEKEND_DIFF_TIME
           ,@SHIFT_WEEKEND_START
           ,@SHIFT_WEEKEND_END
           ,@SHIFT_WEEKEND_BREAK_START
           ,@SHIFT_WEEKEND_BREAK_END
           ,@SHIFT_EARLY_SEARCH_HRS
           ,@SHIFT_LATE_SEARCH_HRS
           ,@SHIFT_ISDELETED
           ,@SHIFT_DELETEDDATE
           ,@SHIFT_START_EARLY_SEARCH_HRS
           ,@SHIFT_START_LATE_SEARCH_HRS
           ,@SHIFT_START_EARLY_VALID_HRS
           ,@SHIFT_START_LATE_VALID_HRS
           ,@SHIFT_BREAK_OUT_EARLY_SEARCH_HRS
           ,@SHIFT_BREAK_OUT_LATE_SEARCH_HRS
           ,@SHIFT_BREAK_OUT_EARLY_VALID_HRS
           ,@SHIFT_BREAK_OUT_LATE_VALID_HRS
           ,@SHIFT_BREAK_IN_EARLY_SEARCH_HRS
           ,@SHIFT_BREAK_IN_LATE_SEARCH_HRS
           ,@SHIFT_BREAK_IN_EARLY_VALID_HRS
           ,@SHIFT_BREAK_IN_LATE_VALID_HRS
           ,@SHIFT_END_EARLY_SEARCH_HRS
           ,@SHIFT_END_LATE_SEARCH_HRS
           ,@SHIFT_END_EARLY_VALID_HRS
           ,@SHIFT_END_LATE_VALID_HRS
           ,@SHIFT_BREAK_OUT_IN_MIN_DUR
           ,@IS_SYNC
           ,@COMPANY_ID)
END
--INSERT ShiftDetails


if(@ActionCommand='Update')
--UPDATE ShiftDetails
BEGIN

UPDATE [dbo].[TA_SHIFT]
   SET [SHIFT_CODE] = @SHIFT_CODE
      ,[SHIFT_DESCRIPTION] = @SHIFT_DESCRIPTION
      ,[SHIFT_ALLOCATION_TYPE] = @SHIFT_ALLOCATION_TYPE
      ,[SHIFT_AUTO_SEARCH_START] = @SHIFT_AUTO_SEARCH_START
      ,[SHIFT_AUTO_SEARCH_END] = @SHIFT_AUTO_SEARCH_END
      ,[SHIFT_TYPE] = @SHIFT_TYPE
      ,[SHIFT_START] = @SHIFT_START
      ,[SHIFT_END] = @SHIFT_END
      ,[SHIFT_BREAK_START] = @SHIFT_BREAK_START
      ,[SHIFT_BREAK_END] = @SHIFT_BREAK_END
      ,[SHIFT_BREAK_HRS] = @SHIFT_BREAK_HRS
      ,[SHIFT_WORKHRS] = @SHIFT_WORKHRS
      ,[SHIFT_FLAG_ADD_BREAK] = @SHIFT_FLAG_ADD_BREAK
      ,[SHIFT_WEEKEND_DIFF_TIME] = @SHIFT_WEEKEND_DIFF_TIME
      ,[SHIFT_WEEKEND_START] = @SHIFT_WEEKEND_START
      ,[SHIFT_WEEKEND_END] = @SHIFT_WEEKEND_END
      ,[SHIFT_WEEKEND_BREAK_START] = @SHIFT_WEEKEND_BREAK_START
      ,[SHIFT_WEEKEND_BREAK_END] = @SHIFT_WEEKEND_BREAK_END
      ,[SHIFT_EARLY_SEARCH_HRS] = @SHIFT_EARLY_SEARCH_HRS
      ,[SHIFT_LATE_SEARCH_HRS] = @SHIFT_LATE_SEARCH_HRS
      ,[SHIFT_ISDELETED] = @SHIFT_ISDELETED
      ,[SHIFT_DELETEDDATE] = @SHIFT_DELETEDDATE
      ,[SHIFT_START_EARLY_SEARCH_HRS] = @SHIFT_START_EARLY_SEARCH_HRS
      ,[SHIFT_START_LATE_SEARCH_HRS] = @SHIFT_START_LATE_SEARCH_HRS
      ,[SHIFT_START_EARLY_VALID_HRS] = @SHIFT_START_EARLY_VALID_HRS
      ,[SHIFT_START_LATE_VALID_HRS] = @SHIFT_START_LATE_VALID_HRS
      ,[SHIFT_BREAK_OUT_EARLY_SEARCH_HRS] = @SHIFT_BREAK_OUT_EARLY_SEARCH_HRS
      ,[SHIFT_BREAK_OUT_LATE_SEARCH_HRS] = @SHIFT_BREAK_OUT_LATE_SEARCH_HRS
      ,[SHIFT_BREAK_OUT_EARLY_VALID_HRS] = @SHIFT_BREAK_OUT_EARLY_VALID_HRS
      ,[SHIFT_BREAK_OUT_LATE_VALID_HRS] = @SHIFT_BREAK_OUT_LATE_VALID_HRS
      ,[SHIFT_BREAK_IN_EARLY_SEARCH_HRS] = @SHIFT_BREAK_IN_EARLY_SEARCH_HRS
      ,[SHIFT_BREAK_IN_LATE_SEARCH_HRS] = @SHIFT_BREAK_IN_LATE_SEARCH_HRS
      ,[SHIFT_BREAK_IN_EARLY_VALID_HRS] = @SHIFT_BREAK_IN_EARLY_VALID_HRS
      ,[SHIFT_BREAK_IN_LATE_VALID_HRS] = @SHIFT_BREAK_IN_LATE_VALID_HRS
      ,[SHIFT_END_EARLY_SEARCH_HRS] = @SHIFT_END_EARLY_SEARCH_HRS
      ,[SHIFT_END_LATE_SEARCH_HRS] = @SHIFT_END_LATE_SEARCH_HRS
      ,[SHIFT_END_EARLY_VALID_HRS] = @SHIFT_END_EARLY_VALID_HRS
      ,[SHIFT_END_LATE_VALID_HRS] = @SHIFT_END_LATE_VALID_HRS
      ,[SHIFT_BREAK_OUT_IN_MIN_DUR] = @SHIFT_BREAK_OUT_IN_MIN_DUR
      ,[IS_SYNC] = @IS_SYNC
      ,[COMPANY_ID] = @COMPANY_ID
 WHERE [SHIFT_ID] = @SHIFT_ID

END
--UPDATE ShiftDetails


if(@ActionCommand='Delete')
--DELETE ShiftDetails
BEGIN
UPDATE [dbo].[TA_SHIFT]
   SET [SHIFT_ISDELETED] = 1
      ,[SHIFT_DELETEDDATE] = GETDATE()
      WHERE [SHIFT_ID] = @SHIFT_ID
END
--DELETE ShiftDetails